.PHONY: clean All

All:
	@echo "----------Building project:[ VariableBasics - Debug ]----------"
	@cd "VariableBasics" && "$(MAKE)" -f  "VariableBasics.mk"
clean:
	@echo "----------Cleaning project:[ VariableBasics - Debug ]----------"
	@cd "VariableBasics" && "$(MAKE)" -f  "VariableBasics.mk" clean
